# Local consumption — apply our own source files to this repo
- self:
  - include: ["src/**"]
  - template: ["src/.github/workflows/release.yaml"]
  - rename:
      - "^src/(.*)$": "$1"
  - yaml:
      auto-merge: .pre-commit-config.yaml
      array_mode: append_unique
  - repo:
      url: https://github.com/common-repo/semantic-release
      ref: v0.5.2
  - template-vars:
      GH_APP_ID_SECRET: COMMON_REPO_BOT_CLIENT_ID
      GH_APP_KEY_SECRET: COMMON_REPO_BOT_PRIVATE_KEY
      GH_APP_OWNER: common-repo

# Source API — what consumers inherit
- include: ["src/**"]
- template: ["src/.github/workflows/release.yaml"]
- rename:
    - "^src/(.*)$": "$1"
- yaml:
    auto-merge: .pre-commit-config.yaml
    array_mode: append_unique
- repo:
    url: https://github.com/common-repo/semantic-release
    ref: v0.5.2
- template-vars:
    GH_APP_ID_SECRET: COMMON_REPO_BOT_CLIENT_ID
    GH_APP_KEY_SECRET: COMMON_REPO_BOT_PRIVATE_KEY
    GH_APP_OWNER: common-repo
